manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 040238a97dfb55ad84867c007944809425f1befe # Dec 17, 2025, 10:04 PM GMT+5
      import: app/west.yml
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: ebbc1f0ccdb51669650bb0ac3e34920d09e62400 # Mar 17, 2025, 12:01 AM GMT+5
    - name: zmk-auto-layer
      remote: urob
      revision: cf52cce16cf798b116b380fc13dfd36b3a998de6 # Dec 10, 2025, 7:17 AM GMT+5
  self:
    path: config
