name: Compile ZMK
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/boards/shields/*.conf"
      - "config/boards/shields/*.overlay"
      - "config/boards/*/*/*.keymap"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@040238a97dfb55ad84867c007944809425f1befe # Dec 17, 2025, 10:04 PM GMT+5
